"""empty message

Revision ID: 117f4810be93
Revises: 82b5cae08c0b
Create Date: 2022-05-25 10:18:52.319475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '117f4810be93'
down_revision = '82b5cae08c0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('past_shows_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'past_shows_count')
    # ### end Alembic commands ###
