"""empty message

Revision ID: 1b777b9684dc
Revises: 66872475c275
Create Date: 2022-05-24 11:44:28.187594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b777b9684dc'
down_revision = '66872475c275'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shows', sa.Column('show_time', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Shows', 'show_time')
    # ### end Alembic commands ###
