"""empty message

Revision ID: 6bfd0f07910b
Revises: 9069287c2532
Create Date: 2022-05-23 15:39:22.217361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bfd0f07910b'
down_revision = '9069287c2532'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Area',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('Venue', sa.Column('area', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Venue', 'Area', ['area'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Venue', type_='foreignkey')
    op.drop_column('Venue', 'area')
    op.drop_table('Area')
    # ### end Alembic commands ###
