"""empty message

Revision ID: 713013ea9989
Revises: 6bfd0f07910b
Create Date: 2022-05-23 15:57:59.680803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '713013ea9989'
down_revision = '6bfd0f07910b'
branch_labels = None
depends_on = None


def upgrade():
    # manually generated migration
    op.alter_column(table_name='Venue', column_name='genre', new_column_name='genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(table_name='Venue', column_name='genres', new_column_name='genre')
    # ### end Alembic commands ###
