"""empty message

Revision ID: dd9efd8abcd9
Revises: 117f4810be93
Create Date: 2022-05-25 12:57:49.263531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd9efd8abcd9'
down_revision = '117f4810be93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('date_listed', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'date_listed')
    # ### end Alembic commands ###
