"""empty message

Revision ID: dfae521dd92a
Revises: 1b777b9684dc
Create Date: 2022-05-24 12:04:54.633343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfae521dd92a'
down_revision = '1b777b9684dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shows', sa.Column('artist_name', sa.String(length=100), nullable=True))
    op.add_column('Shows', sa.Column('venue_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Shows', 'venue_name')
    op.drop_column('Shows', 'artist_name')
    # ### end Alembic commands ###
